# Arrays
- Array Creation
- Built-in array creating routines
- Creating random number arrays
- Array attributes
- Array methods

A NumPy array is a grid of values, all of the same type, indexed by a tuple of non-negative integers.

## [Array creation](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation)

Creating NumPy Arrays with [np.array()](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [2]:
import numpy as np # Start by importing the library

Create a vector by casting a list to an array

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

Create a matrix by casting a list of lists to an array

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy [built-in array creating routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation)

NumPy has many different ways built-in that will allow you to quickly create arrays

### [.arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

arange returns an array of evenly spaced values over a given interval

`np.arange(start,stop)`


In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### [.zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

zeros returns an array of zeros

1d - `np.zeros(n)`
2d - `np.zeros((n,n))`

In [8]:
np.zeros(5) # create an array of five zeros

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5)) # create a five by five array of zeroes, notice how 2d arrays are created using a tuple of values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### [.ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

ones returns an array of ones

1d - `np.ones(n)`
2d - `np.ones((n,n))`

In [11]:
np.ones(5) # create an array of five ones

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5)) # create a five by five array of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### [.linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

linspace returns an array of evenly spaced numbers over a specified interval

`np.linspace(start,stop,n)`

In [14]:
np.linspace(1,3,3)  # create an array of three evenly space numbers between one and three

array([1., 2., 3.])

In [15]:
np.linspace(0,1,10) # create an array of ten evenly spaced numbers between zero and one

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### [.eye()](https://numpy.org/devdocs/reference/generated/numpy.eye.html)

eye creates an [identity matrix](https://en.wikipedia.org/wiki/Identity_matrix)

`np.eye(n)`

In [16]:
np.eye(5)   # create a 5 by 5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Creating random number arrays

[.random.rand()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

rand returns an array of random numbers from a [Uniform distribution](https://mathworld.wolfram.com/UniformDistribution.html)

1d - `np.random.rand(n)`
2d - `np.random.rand(n,n)`

In [17]:
np.random.rand(5)   # create an array of five numbers from a Uniform distribution

array([0.93079953, 0.16024721, 0.1522763 , 0.14377352, 0.18182003])

In [18]:
np.random.rand(5,5) # create a five by five matrix of numbers from a Uniform distribution

array([[6.78890408e-01, 6.64256409e-01, 5.38170434e-01, 4.40085244e-02,
        9.32066296e-01],
       [7.04255815e-01, 5.18742724e-01, 5.41277007e-01, 2.14566805e-01,
        6.21215496e-01],
       [7.77988923e-01, 5.88862703e-02, 3.46889732e-04, 4.07973065e-01,
        1.37816216e-01],
       [7.53043727e-01, 1.24874763e-01, 5.45411762e-01, 9.64070422e-01,
        2.25646785e-01],
       [1.13384360e-01, 7.69118694e-01, 4.56389451e-03, 9.25966114e-01,
        4.25473388e-01]])

[.random.randn()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

randn returns an array of random numbers from a [Standard Normal distribution](https://mathworld.wolfram.com/NormalDistribution.html)

1d - `np.random.randn(n)`
2d -`np.random.randn(n,n)`

In [19]:
np.random.randn(5)  # create a five by five matrix of numbers from a Normal distribution

array([ 2.24341315,  1.31672588,  0.15221717, -1.54175564,  1.74593415])

In [20]:
np.random.randn(5,5)

array([[ 1.07589399,  0.93873707, -0.14394717, -0.14489925, -0.51109647],
       [-1.27436377,  1.4586825 ,  0.14458712,  1.36912496,  0.30797205],
       [ 0.19168567, -0.56867208,  0.57368984,  0.87457782,  1.01974625],
       [ 0.10617579,  0.22347777, -0.03731724,  0.30325902, -0.84801188],
       [-0.70891641, -0.09705344, -0.28254932, -0.81362657,  1.21889331]])

[.random.randint()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

randint returns random integers, exclusive of `high`, `size` is optional

`np.random.randint(low,high,size)`


In [21]:
np.random.randint(1,101)    # generate a random number between 1 and 100

34

In [22]:
np.random.randint(1,101,10) # generate ten random numbers between 1 and 100

array([91, 38, 14, 43, 38, 90, 97, 95, 96, 65])

## [Array attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#:~:text=Array%20attributes%20reflect%20information%20that,without%20creating%20a%20new%20array.)

Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array.

Two key attributes you will want to know about arrays are their shape and data type.


In [23]:
arr = np.arange(20) # Create an array of 20 evenly spaced values
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
arr.shape   # Notice how the output is 20 rows

(20,)

In [25]:
arr.dtype   # 64-bit integers

dtype('int64')

In [28]:
arr2 = np.random.randn(20,20)   # Create a 20 by 20 matrix of random numbers from a normal distribution
arr2

array([[-0.08955625,  0.13473197, -0.16669705, -1.3943698 ,  0.91731906,
        -0.50044625, -0.05839422,  0.34108881,  0.25427774,  1.55167271,
        -1.16009673, -0.40935537, -0.68428276,  0.40355083,  0.25698209,
         0.44053071,  1.06314899, -1.42342029,  2.01190387, -0.25298281],
       [ 1.46473799,  0.66528716,  1.3764596 ,  1.71681558, -0.55282272,
         0.23740833, -0.82743943,  1.14232611, -1.22113029, -1.07564094,
         0.00840319, -0.55365401,  0.36034392, -1.61191503,  0.25875797,
        -2.82240025,  0.27455183,  0.9098267 ,  0.22261205,  1.25396343],
       [ 0.48419258, -1.98108054,  0.18408874,  0.73922696, -0.46186534,
         1.00346508,  2.09871535, -1.28839589,  0.80160553,  0.17719455,
         1.01688756,  1.00980916,  0.41473812,  0.54275306,  0.69876006,
        -1.76972615, -0.3053793 , -0.36766699, -0.10827756,  2.10192205],
       [ 0.04094074,  0.68544964, -0.87902787,  0.59967228, -0.2574219 ,
         2.22585715, -0.8467173 ,  1.11119063, -

In [30]:
arr2.shape  # Notice how the output is 20 rows and 20 columns

(20, 20)

In [31]:
arr2.dtype  # 64-bit floating point number

dtype('float64')

## [Array Methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [44]:
arr3 = np.random.randint(1,100,25) # Create an array of 25 random numbers between 1 and 99
arr3

array([63, 34, 61, 72, 75,  5, 79, 19, 72, 69, 70, 39, 11, 72, 88, 20, 45,
       44, 42, 95, 48, 61, 50, 99, 25])

Reshape an array with [.reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [47]:
arr3 = arr3.reshape(5,5)
arr3

array([[63, 34, 61, 72, 75],
       [ 5, 79, 19, 72, 69],
       [70, 39, 11, 72, 88],
       [20, 45, 44, 42, 95],
       [48, 61, 50, 99, 25]])

Find the max value in an array with [.max()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html)

In [49]:
arr3.max()

99

Find the index location of the max value in an array with [.argmax()](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

In [51]:
arr3.argmax()

23

Find the min value in an array with [.min()](https://numpy.org/doc/stable/reference/generated/numpy.minimum.html)

In [52]:
arr3.min()

5

Find the index location of the min value in an array with [.argmin()](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)

In [53]:
arr3.argmin()

5