# [Indexing and Slicing](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing)
- Indexing and Slicing 1D arrays
- Indexing and Slicing 2D matrices

Indexing and Slicing can be confusing at first so it can be helpful to work through a [video tutorial](https://www.youtube.com/watch?v=c4kX6jgxwos)

In [2]:
import numpy as np

## Indexing and Slicing 1D arrays

In [9]:
arr = np.arange(0,11) # Create an array of 10 evenly spaced values
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

NumPy indices uses bracket notation the same as Python iterables such as lists

In [5]:
arr[5]  # Get value at index 5

5

In [6]:
arr[5:11]   # Get values from index 5 to index 10 (remember up to but not including)

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[::2]    # Get every other value from index 0

array([ 0,  2,  4,  6,  8, 10])

## Indexing and Slicing 2D matrices

Indexing format for matrices use the bracket notation `[rows,columns]` or `[rows][columns]` the former is more common

In [10]:
arr2 = np.arange(0,25) # Create an array of 25 evenly spaced values
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr2 = arr2.reshape(5,5) # Reshape to a 5 by 5 matrix
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Indexing

In [15]:
arr2[0] # Indexing by row (row 0)

array([0, 1, 2, 3, 4])

In [18]:
arr2[:,0]  # Indexing by column  (column 0)

array([ 0,  5, 10, 15, 20])

In [20]:
arr2[2,2]   # Get value from row 2 column 2

12

### Slicing

In [25]:
arr2[:2,0:2]   # (2,2) slice from top left corner

array([[0, 1],
       [5, 6]])

In [26]:
arr2[:2,3:] # (2,2) slice from top right corner

array([[3, 4],
       [8, 9]])

In [27]:
arr2[3:,:2] # (2,2) slice from bottom left corner

array([[15, 16],
       [20, 21]])

In [28]:
arr2[3:,3:] # (2,2) slice from bottom right corner

array([[18, 19],
       [23, 24]])

In [29]:
arr2[1:4,1:4]   # (3,3) slice from the middle

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])