# NumPy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)   # Create an array of ten even spaced values between zero and ten

# Array by Array
Operations on an element-by-element basis

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Add two Arrays together on an element-by-element basis

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Subtract

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Multiply

In [8]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Array by Scalar
Scalars are just a single number
NumPy broadcasts that scalar to every element so also on element-by-element basis

Addition

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

Multiplication

In [10]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

# Universal Array Functions
Full list of [Universal Array Functions](https://numpy.org/doc/stable/reference/ufuncs.html)
Full list of [Mathematical NumPy functions](https://numpy.org/doc/stable/reference/routines.math.html)

Take the square root of every element in an array with [.sqrt()](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

Calculate the exponential of every element in an array with [.exp()](https://numpy.org/doc/stable/reference/generated/numpy.exp.html)

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

Find the maximum value in an array with [.max()](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html)

In [13]:
np.max(arr)

10

You can use trigonmetric functions

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

And logarithmic functions

In [15]:
np.log(arr)

<ipython-input-15-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

Most mathematical operations are already built into NumPy, so it's always worth checking the docs

A [handy list of NumPy cheatsheets](https://blog.finxter.com/collection-10-best-numpy-cheat-sheets-every-python-coder-must-own/)